import test from 'node:test';
import assert from 'node:assert/strict';
import { database, env, network, callback, command, article } from './support.js';
import { handleUpdate, menu } from '../src/bot.js';
import { render } from '../src/navigation.js';
import { cleanup, DAY } from '../src/db.js';

const now = 1_800_000_000;
const view = n => n.requests.at(-1).body;
const buttons = n => view(n).reply_markup.inline_keyboard.flat();
const find = (n, text) => buttons(n).find(b => b.text === text)?.callback_data;
const click = (e, n, data, chat = 1, time = now) => handleUpdate(e, callback(chat, data), n.net, time);

test('focused menu edits one message, preserves page and parent, and hides unconfigured AI', async () => {
  const DB = database(), e = env(DB), n = network();
  await handleUpdate(e, command(1, '/start'), n.net, now);
  assert.equal(buttons(n).length, 3);
  assert.match(view(n).text, /Choose a few topics|20:00/);
  await click(e, n, find(n, 'Choose categories'));
  assert.match(view(n).text, /Categories · 1\/3/);
  assert.equal(buttons(n).filter(b => b.callback_data?.startsWith('cat:')).length, 5);
  await click(e, n, find(n, 'Next →'));
  const subscribe = buttons(n).find(b => b.text.includes('Business'));
  assert.match(subscribe.text, /Toyo Keizai/);
  await click(e, n, subscribe.callback_data);
  assert.match(view(n).text, /Categories · 2\/3/);
  assert.match(buttons(n).find(b => b.text.includes('Business')).text, /^✓/);
  await click(e, n, find(n, '← Back'));
  assert.match(view(n).text, /Topics:<\/b> Business/);
  await click(e, n, find(n, 'Settings'));
  assert.equal(buttons(n).some(b => /AI/.test(b.text)), false);
  await click(e, n, find(n, 'Articles per digest'));
  await click(e, n, find(n, '10'));
  assert.match(view(n).text, /Currently: up to 10/);
  await click(e, n, find(n, '← Back'));
  await click(e, n, find(n, 'Delivery times'));
  await click(e, n, 'manual');
  assert.match(view(n).text, /Manual only/);
  await click(e, n, 'slot:morning:1');
  assert.match(view(n).text, /Japan 07:00\nMoscow 01:00/);
  await click(e, n, find(n, '← Back'));
  await click(e, n, find(n, 'Pause delivery'));
  assert.match(view(n).text, /paused/);
  const before = await DB.prepare('SELECT * FROM users WHERE chat_id=1').first();
  await click(e, n, find(n, 'Categories'));
  await click(e, n, find(n, 'Next →'));
  await click(e, n, find(n, '← Previous'));
  await click(e, n, find(n, '← Back'));
  assert.match(view(n).text, /<b>Settings/);
  assert.deepEqual(await DB.prepare('SELECT * FROM users WHERE chat_id=1').first(), before);
  assert.equal(n.messages.length, 1);
  assert.ok(n.requests.filter(r => r.url.endsWith('/editMessageText')).every(r => r.body.message_id === 9));
  Object.assign(e, { OPENROUTER_API_KEY: 'fake', OPENROUTER_MODEL: 'test/model', AI_ALLOWED_CHAT_IDS: '1' });
  assert.ok(menu(before, 'settings', 0, 'home', e).keyboard.flat().some(b => b.text === 'AI language'));
  assert.equal(menu({ ...before, chat_id: 2 }, 'settings', 0, 'home', e).keyboard.flat().some(b => b.text === 'AI language'), false);
});

test('digest pagination marks only visible articles, supports article back, and scopes saved actions', async () => {
  const DB = database(), e = env(DB), n = network();
  await click(e, n, 'cat:news:1');
  await click(e, n, 'count:10');
  for (let i = 0; i < 10; i++) await article(DB, 'news', i, now);
  await click(e, n, 'news');
  assert.match(view(n).text, /Your news · 1\/2/);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM deliveries').first()).n, 5);
  const session = (await DB.prepare('SELECT id FROM reader_sessions').first()).id;
  assert.equal(buttons(n).filter(b => /Save|Translate|Explain/.test(b.text)).length, 0);
  await click(e, n, find(n, 'Next →'));
  assert.match(view(n).text, /Your news · 2\/2/);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM deliveries').first()).n, 10);
  await click(e, n, find(n, 'Article details'));
  assert.match(view(n).text, /Article 6\/10/);
  assert.equal(find(n, '← Back'), `digest:${session}:1`);
  const save = find(n, 'Save for later');
  await click(e, n, save);
  await click(e, n, save); // A repeated stale click sets the desired state.
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM bookmarks').first()).n, 1);
  assert.ok(find(n, 'Remove from Read later'));
  await click(e, n, find(n, '← Previous'));
  assert.match(view(n).text, /Article 5\/10/);
  assert.equal(find(n, '← Back'), `digest:${session}:0`);
  await click(e, n, find(n, '← Back'));
  assert.match(view(n).text, /Your news · 1\/2/);
  await click(e, n, 'news', 1, now + 1);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM reader_sessions').first()).n, 1);
  Object.assign(e, { OPENROUTER_API_KEY: 'fake', OPENROUTER_MODEL: 'test/model', AI_ALLOWED_CHAT_IDS: '1' });
  await click(e, n, `translate:${session}:5`);
  assert.equal(n.aiCalls, 1);
  assert.equal(find(n, '← Back'), `article:${session}:5`);
  await click(e, n, find(n, '← Back'));
  assert.match(view(n).text, /Article 6\/10/);
  await click(e, n, `article:${session}:5`, 2);
  assert.match(view(n).text, /no longer available/);
  assert.doesNotMatch(view(n).text, /Headline news/);
  await click(e, n, `keep:${session}:5:0`, 2);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM bookmarks').first()).n, 1);
  await cleanup(DB, now + 8 * DAY);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM reader_sessions').first()).n, 0);
});

test('saved pages and article navigation survive cache eviction, and removal returns to a valid page', async () => {
  const DB = database(), e = env(DB), n = network();
  await click(e, n, 'cat:news:1');
  await click(e, n, 'count:10');
  for (let i = 0; i < 6; i++) await article(DB, 'news', i, now);
  await click(e, n, 'news');
  await click(e, n, find(n, 'Next →'));
  const session = (await DB.prepare('SELECT id FROM reader_sessions').first()).id;
  for (let i = 0; i < 6; i++) await click(e, n, `keep:${session}:${i}:1`);
  await cleanup(DB, now + 31 * DAY);
  await click(e, n, 'page:saved:0:home');
  assert.match(view(n).text, /Read later · 1\/2/);
  assert.equal(buttons(n).filter(b => /Remove/.test(b.text)).length, 0);
  await click(e, n, find(n, 'Next →'));
  assert.match(view(n).text, /Read later · 2\/2/);
  await click(e, n, find(n, 'Read article'));
  assert.match(view(n).text, /Saved article 6\/6/);
  assert.equal(buttons(n)[0].url, 'https://example.org/news/0');
  assert.equal(find(n, '← Back'), 'page:saved:1:home');
  const drop = find(n, 'Remove from Read later');
  await click(e, n, drop, 2);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM bookmarks').first()).n, 6);
  await click(e, n, drop);
  assert.match(view(n).text, /<b>Read later<\/b>/);
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM bookmarks').first()).n, 5);
  assert.ok(find(n, '← Back'));
});

test('unchanged-message edits are harmless, but failed edits leave articles unread', async () => {
  const DB = database(), e = env(DB), n = network();
  await click(e, n, 'cat:news:1');
  await article(DB, 'news', 0, now);
  const fail = async () => Response.json({ ok: false, error_code: 400, description: 'Bad Request: invalid reply markup' });
  await assert.rejects(handleUpdate(e, callback(1, 'news'), fail, now));
  assert.equal((await DB.prepare('SELECT count(*) AS n FROM deliveries').first()).n, 0);
  await render(e, 1, 'Same', [], async () => Response.json({ ok: false, error_code: 400, description: 'Bad Request: message is not modified' }), 9);
});
